language: php

sudo: required

php:
- "7.2"

dist: xenial

services:
- mysql

addons:
  apt:
    packages:
    - mysql-server
    - mysql-client
  chrome: stable

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

before_script:
# Install Node.js and build JS/CSS.
- nvm install stable
- npm ci
- npm run prod
# Install Imagick
- pear config-set preferred_state beta
- pecl channel-update pecl.php.net
- yes | pecl install imagick
# Install Composer dependencies
- composer install --no-interaction
# Setup headless web browser for Laravel Dusk tests
- php artisan dusk:chrome-driver
- export DISPLAY=:99.0
- ./vendor/laravel/dusk/bin/chromedriver-linux &
# Create database, migrate & seed
- mysql -e 'CREATE DATABASE IF NOT EXISTS test_database;'
- php artisan migrate:refresh --seed
# Start web server
- php artisan serve >/dev/null 2>&1 &

script:
# Run PHPUnit & Laravel Dusk tests
- vendor/bin/phpunit --coverage-clover=coverage.xml
- php artisan dusk

env:
  global:
  - LANG=en_GB.UTF-8
  - LC_ALL=en_GB.UTF-8

  - APP_NAME=Laravel
  - APP_ENV=local
  - APP_KEY=base64:DcAioZro7e+VqYWHs/xvW5fzGGoiItIl38FZ2aiA3ew=
  - APP_DEBUG=true
  - APP_URL=http://127.0.0.1:8000

  - LOG_CHANNEL=stack
  - DB_CONNECTION=mysql
  - DB_HOST=127.0.0.1
  - DB_PORT=3306
  - DB_DATABASE=test_database
  - DB_USERNAME=root
  - DB_PASSWORD=

  - BROADCAST_DRIVER=log
  - CACHE_DRIVER=file
  - SESSION_DRIVER=file
  - SESSION_LIFETIME=200
  - QUEUE_DRIVER=sync

  - REDIS_HOST=127.0.0.1
  - REDIS_PASSWORD=null
  - REDIS_PORT=6379

  - MAIL_DRIVER=ses
  - MAIL_HOST=smtp.mailtrap.io
  - MAIL_PORT=2525
  - MAIL_USERNAME=null
  - MAIL_PASSWORD=null
  - MAIL_ENCRYPTION=null

  - PUSHER_APP_ID=
  - PUSHER_APP_KEY=
  - PUSHER_APP_SECRET=
  - PUSHER_APP_CLUSTER=mt1

  - MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
  - MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
